config/routes.rb
Rails.application.routes.draw do
  # get 'commits/index'
  # get 'commits/show'
  # get 'commits/edit'
  # get 'commits/new'
  
  # get 'realestates/index'
  # get 'realestates/show'
  # get 'realestates/new'
  # get 'realestates/edit'

  resources :realestates do
    resources :commits

  end
  devise_for :users
  # get '/homes', to: 'homes#index'
  root "homes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
class Commit < ApplicationRecord
  belongs_to :realestate
end

app/models/realestate.rb
class Realestate < ApplicationRecord
    belongs_to :user
    has_many :commits, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :realestates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        realestates_path
    end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  end

  def create 
    @realestate=Realestate.find(params[:realestate_id])
    @commit=@realestate.commits.new(commit_params)
    #@commemt.user_id=session[:user].to_i
    @commit.save
    redirect_to realestate_path(@realestate)

end

private 
def commit_params
  params.require(:commit).permit(:comment)
end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @realestates = Realestate.all
  end
end

app/controllers/realestates_controller.rb
class RealestatesController < ApplicationController
  
  before_action :authenticate_user!, only: [:index,:new,:edit,:update,:destroy,:create]

  def index
    user_id = current_user.id
    @user = User.find(user_id)
    @realestates = @user.realestates
  end

  def show
    @realestate = Realestate.find(params[:id])
    @commit = @realestate.commits.new
    @user = User.find(@realestate.user_id)
  end

  def new
    @realestate = Realestate.new 
    #{title:nil,details:nil,User_id:nil}
  end



  def edit
   @realestate = Realestate.find(params[:id])
  end

  def update
    @realestate = Realestate.find(params[:id]) 
    @realestate.update(realestate_params)
    redirect_to realestates_path
  
  
  end
  def create 
    user_id = current_user.id
    @realestate = Realestate.create(realestate_params)
    @realestate.user_id = user_id
    @realestate.save
    redirect_to realestates_path
  end 

  def destroy
    
    @realestate = Realestate.find(params[:id])
    @realestate.destroy
    redirect_to realestates_path
  end

  private
  def realestate_params 
    return params.require(:realestate).permit(:title,:details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/realestates_helper.rb
module RealestatesHelper
end

app/views/commits/edit.html.erb
<h1>Commits#edit</h1>
<p>Find me in app/views/commits/edit.html.erb</p>

app/views/commits/index.html.erb
<h1>Commits#index</h1>
<p>Find me in app/views/commits/index.html.erb</p>

app/views/commits/new.html.erb
<h1>Commits#new</h1>
<p>Find me in app/views/commits/new.html.erb</p>

app/views/commits/show.html.erb
<h1>Commits#show</h1>
<p>Find me in app/views/commits/show.html.erb</p>

app/views/homes/index.html.erb
<%# <h1>Homes#index</h1> %>
<table class="table table-striped table-dark">
<tr> 
<th>id</th>
<th>title</th>
<th>details</th>
</tr>
<% @realestates.each do |real|%>

<tr>
<td><%= real.id%></td>
<td><%= real.title%></td>
<td> <%= real.details%></td>
<td> <%= link_to "show", realestate_path(real)%></td>

</tr>
<%end%>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppRealestate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>


  <button type="button" class="btn btn-dark"><%= link_to "Home ", root_path%></button>
  <% if user_signed_in? %>
  <button type="button" class="btn btn-dark"><%= link_to "My Realestates", realestates_path	%></button>
  <button type="button" class="btn btn-dark"><%= link_to "Add New Realestate", new_realestate_path%></button>
  <button type="button" class="btn btn-dark"><%= link_to(" Sign Out", destroy_user_session_path, method: :delete)%></button>
  <%else%>
   <button type="button" class="btn btn-dark"><%= link_to " Login ", new_user_session_path%></button>
    <button type="button" class="btn btn-dark"><%= link_to " Signup ", new_user_registration_path%></button>
  <%end%>
   
  <nav>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/realestates/edit.html.erb
<h1>Realestates#edit</h1>
<%=form_for @realestate,url:{action:"update"} do |f| %>
<%= f.label :title%>
<%= f.text_field :title%>
<%= f.label :details%>
<%= f.text_area :details , cols: "50", rows: "5"%>
<button type="button" class="btn btn-dark"><%= f.submit "update"%></button>

<% end%>

app/views/realestates/index.html.erb
<h1>Realestates#index</h1>
<table class="table table-striped table-dark">
<tr>
    <th>ID</th>
    <th>TITLE</th>
    <th>DETAILS</th>
</tr>
<% @realestates.each do  |realestate|%>
    <tr>
        <td> <%= realestate.id %></td>
        <td> <%= realestate.title %></td>
        <td> <%= realestate.details %></td>
        <td> <%= link_to "show", realestate_path(realestate)%></td>
        <td> <%= link_to "edit", edit_realestate_path(realestate)%></td>
        <td> <%= link_to "deleteee", realestate_path(realestate), method: :DELETE %> </td>
    </tr>
<%end%>
</table>

app/views/realestates/new.html.erb
<%# <h1>Realestates#new</h1> %>

<div>
<%= form_for @realestate,url:{action:"create"} do |f| %>
<div>
<%= f.label :title%>
<%= f.text_field :title%>
</div>
<br>

<div class="form-group">
<%= f.label :details%>
<%= f.text_area :details , cols: "50", rows: "5"%>
</div>

<div>
<br>
<%= f.submit "Save" %>
</div>

</div>


<%end%>

app/views/realestates/show.html.erb
<h1>Realestates#show</h1>
<%= @realestate.title %>
<br>
<%= @realestate.details %>
<br>
<label>Email of User: </label>


<%= @user.email %>

<h1> View Commit</h1>

<table> 
<thead>
<tr>
<th>comments</th>
</tr>
</thead>
<tbody>
<br>
<% @realestate.commits.each do |commit|%>
<tr>
<td> <%=commit.comment%></td>
<td><%# comment.user.email %></td>
</td>
</tr>
<% end %>

</tbody>

</table>
<% if user_signed_in? %>
<h1>Add Commit</h1>
<%= form_for [@realestate,@commit] do |f| %>


<div class = "field">
<%= f.label :comment%>
</div>

<div>
<%= f.text_area :comment, cols:30,rows:5%>
</div>

<div class = "action">
    <%= f.button "Save"%>
</div>
<% end %>


<% end %>